# Gravity Cluster Configuration - Four Validator Suite

[cluster]
name = "gravity-devnet-four"
base_dir = "/tmp/gravity-cluster-four"

[build]
binary_path = "../target/quick-release/gravity_node"

[dependencies.genesis_contracts]
repo = "https://github.com/Galxe/gravity_chain_core_contracts.git"
ref = "main"

[[nodes]]
id = "node1"
role = "genesis"
host = "127.0.0.1"
p2p_port = 6180
vfn_port = 6190
rpc_port = 8545
metrics_port = 9001
inspection_port = 10000
https_port = 1024
authrpc_port = 8551
reth_p2p_port = 12024

[[nodes]]
id = "node2"
role = "genesis"
host = "127.0.0.1"
p2p_port = 6181
vfn_port = 6191
rpc_port = 8546
metrics_port = 9002
inspection_port = 10001
https_port = 1025
authrpc_port = 8552
reth_p2p_port = 12025

[[nodes]]
id = "node3"
role = "genesis"
host = "127.0.0.1"
p2p_port = 6182
vfn_port = 6192
rpc_port = 8547
metrics_port = 9003
inspection_port = 10002
https_port = 1026
authrpc_port = 8553
reth_p2p_port = 12026

[[nodes]]
id = "node4"
role = "genesis"
host = "127.0.0.1"
p2p_port = 6183
vfn_port = 6193
rpc_port = 8548
metrics_port = 9004
inspection_port = 10003
https_port = 1027
authrpc_port = 8554
reth_p2p_port = 12027

[genesis]
epoch_interval_micros = 7200000000
major_version = 1
consensus_config = "0x00"
execution_config = "0x00"

[[genesis.faucet]]
address = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
balance = "0x2000000000000000000000000000000000000000000000000000000000000000"


[genesis.validator_config]
minimum_bond = "1000000000000000000"
maximum_bond = "1000000000000000000000000"
unbonding_delay_micros = 604800000000
allow_validator_set_change = true
voting_power_increase_limit_pct = 20
max_validator_set_size = "100"

[genesis.staking_config]
minimum_stake = "1000000000000000000"
lockup_duration_micros = 86400000000
unbonding_delay_micros = 86400000000
minimum_proposal_stake = "10000000000000000000"

[genesis.governance_config]
min_voting_threshold = "1000000000000000000"
required_proposer_stake = "10000000000000000000"
voting_duration_micros = 604800000000

[genesis.randomness_config]
variant = 0
secrecy_threshold = 0
reconstruction_threshold = 0
fast_path_secrecy_threshold = 0

[genesis.oracle_config]
source_types = [1]
callbacks = ["0x00000000000000000000000000000001625F2018"]

[genesis.jwk_config]
issuers = ["0x68747470733a2f2f6163636f756e74732e676f6f676c652e636f6d"]

[[genesis.jwk_config.jwks]]
kid = "f5f4c0ae6e6090a65ab0a694d6ba6f19d5d0b4e6"
kty = "RSA"
alg = "RS256"
e = "AQAB"
n = "2K7epoJWl_aBoYGpXmDBBiEnwQ0QdVRU1gsbGXNrEbrZEQdY5KjH5P5gZMq3d3KvT1j5KsD2tF_9jFMDLqV4VWDNJRLgSNJxhJuO_oLO2BXUSL9a7fLHxnZCUfJvT2K-O8AXjT3_ZM8UuL8d4jBn_fZLzdEI4MHrZLVSaHDvvKqL_mExQo6cFD-qyLZ-T6aHv2x8R7L_3X7E1nGMjKVVZMveQ_HMeXvnGxKf5yfEP0hIQlC_kFm4L_1kV1S0UPmMptZL2qI4VnXqmqI6TZJyE-3VXHgNn1Z1O_9QZlPC0fF0spLHf2S3nNqI0v3k2E7q3DkqxVf5xvn7q_X-gPqzVE9Jw"
